/**
 * Generates web-sized copies of the phone originals in `pictures/` into
 * `pictures/web/`. The originals stay untouched — they are the source of truth.
 *
 * Usage:
 *   npm run optimize:images            JPEG only (what the site imports)
 *   npm run optimize:images -- --webp  also emit WebP, for comparison
 *
 * Re-run after adding or replacing a photo, then commit the regenerated files.
 * This is a manual step rather than a `prebuild` hook so CI stays fast and
 * deterministic: the outputs are committed, so the GitHub Pages workflow never
 * has to run sharp.
 *
 * On WebP: measured at quality 80 it came out only ~3% smaller in total than
 * mozjpeg, and was actually *larger* for the hero and the living room. That is
 * not worth giving up universal format support or hand-rolling a `<picture>`
 * element for, so JPEG is what the components import and WebP is opt-in.
 *
 * Note: sharp drops EXIF by default, so the GPS coordinates the phone embedded
 * in these photos do not reach the published site.
 */
import { mkdir, readdir, stat } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC_DIR = path.join(ROOT, 'pictures');
const OUT_DIR = path.join(SRC_DIR, 'web');

const QUALITY = 80;
const WITH_WEBP = process.argv.includes('--webp');

/**
 * `maxEdge` constrains the longer side. The hero is full-bleed at
 * `sizes="100vw"` so it gets 2000px; gallery tiles never exceed half the
 * viewport, so 1600px is already generous on a 2x display.
 *
 * The Rhön landscape is shared by the hero and the "Umgebung" gallery tile.
 * Emitting it once at the hero size means the browser downloads a single file
 * and reuses it for the tile, rather than fetching a second, smaller copy.
 */
const IMAGES = [
  { src: 'PXL_20220312_125022632.jpg', out: 'rhoen-landschaft', maxEdge: 2000 },
  { src: 'PXL_20260814_181503048.MP.jpg', out: 'wohnzimmer', maxEdge: 1600 },
  { src: 'PXL_20260814_173422846.jpg', out: 'kueche', maxEdge: 1600 },
  { src: 'PXL_20260814_175019383.MP.jpg', out: 'bad', maxEdge: 1600 },
  { src: 'BlickAufWasserkuppe.jpeg', out: 'wasserkuppe', maxEdge: 1600 },
  { src: 'BlickVonMaulkuppeAufDieMilseburg.jpeg', out: 'milseburg', maxEdge: 1600 },
];

const kb = (bytes) => `${(bytes / 1024).toFixed(0)} KB`;

async function convert({ src, out, maxEdge }) {
  const input = path.join(SRC_DIR, src);
  const before = (await stat(input)).size;

  // `.rotate()` with no argument applies the EXIF orientation tag before
  // resizing, so portrait phone shots do not come out sideways once the
  // metadata is stripped.
  const pipeline = sharp(input)
    .rotate()
    .resize({ width: maxEdge, height: maxEdge, fit: 'inside', withoutEnlargement: true });

  const jpeg = await pipeline
    .clone()
    .jpeg({ quality: QUALITY, progressive: true, mozjpeg: true })
    .toFile(path.join(OUT_DIR, `${out}.jpg`));

  const webp = WITH_WEBP
    ? await pipeline.clone().webp({ quality: QUALITY }).toFile(path.join(OUT_DIR, `${out}.webp`))
    : null;

  console.log(
    `${src}\n  ${kb(before)} -> ${jpeg.width}x${jpeg.height}  jpg ${kb(jpeg.size)}` +
      (webp ? `  webp ${kb(webp.size)}` : '')
  );

  return { before, jpeg: jpeg.size, webp: webp?.size ?? 0 };
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  const results = [];
  for (const image of IMAGES) {
    results.push(await convert(image));
  }

  const sum = (key) => results.reduce((total, r) => total + r[key], 0);
  console.log(
    `\noriginals ${kb(sum('before'))}  ->  jpeg ${kb(sum('jpeg'))}` +
      (WITH_WEBP ? `  webp ${kb(sum('webp'))}` : '')
  );

  // Guard against a stale import: anything left in pictures/web/ that this run
  // did not produce is dead weight and easy to miss in review.
  const expected = new Set(
    IMAGES.flatMap(({ out }) => (WITH_WEBP ? [`${out}.jpg`, `${out}.webp`] : [`${out}.jpg`]))
  );
  const orphans = (await readdir(OUT_DIR)).filter((name) => !expected.has(name));
  if (orphans.length > 0) {
    console.warn(`\nnot generated by this run, safe to delete: ${orphans.join(', ')}`);
  }
}

await main();
